# fly.toml file generated for udp-test-1 on 2022-01-04T18:05:37+01:00

app = "udp-test-1"

kill_signal = "SIGINT"
kill_timeout = 300
processes = []

[env]
  ADDRESS = "fly-global-services"
  PORT = 8080

[[services]]
  internal_port = 8080
  protocol = "udp"

  [[services.ports]]
    port = "8080"
